import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import toast, { Toaster } from "react-hot-toast";
import ShareRoom from "../components/ShareRoom";
import { trpc } from "../utils/trpc";
import { FaPiedPiperHat } from "react-icons/fa";
import { useUser } from "../utils/useUser";

const MyRoom = () => {
  const [user] = useUser();

  const { data, isLoading, refetch } = trpc.proxy.rooms.getByUser.useQuery({ userId: user.id });

  const { mutateAsync } = trpc.proxy.rooms.create.useMutation();

  const handleCreateRoom = async () => {
    await toast.promise(mutateAsync({ userId: user.id }), {
      loading: "Getting you room ready...",
      success: "All done! Your room is ready.",
      error: (err) => `Oops something went wrong: ${err}`
    });
    await refetch();
  };

  if (isLoading)
    return (
      <div className="flex flex-col text-center items-center">
        <h1 className="text-4xl font-semibold">Checking available rooms...</h1>
        <FaPiedPiperHat size={48} className="mt-12 text-violet-500" />
      </div>
    );

  if (!data)
    return (
      <div className="flex flex-col text-center">
        <h1 className="text-4xl font-semibold">
          Set up your planning poker in seconds, start estimating story points in scrum poker now
        </h1>
        <p className="mt-6 text-lg text-slate-600">
          Create your planning room and invite others with a single click
        </p>
        <button
          className="self-center mt-6 px-4 py-2 rounded-full bg-violet-500 text-white font-semibold uppercase"
          onClick={handleCreateRoom}
        >
          Create Instant Room
        </button>
      </div>
    );

  return (
    <div className="flex flex-col text-center">
      <ShareRoom roomId={data.id} />
      <h1 className="mt-12 text-4xl font-semibold">
        A personal poker room has been assigned to you.
      </h1>
      <p className="mt-6 text-lg text-slate-600">
        Share the room id with your team mates so they can join the scrum poker.
      </p>
      <div className="mt-6 text-slate-600 uppercase">YOUR ROOM ID: {data.id}</div>
      <Link href={`/room/${data.id}`}>
        <button className="self-center mt-6 px-4 py-2 rounded-full bg-violet-500 text-white font-semibold uppercase">
          Enter Your Room
        </button>
      </Link>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 App - ScrumPoker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen container mx-auto px-4 grid justify-center content-center">
        <MyRoom />
        <Toaster />
      </main>
    </>
  );
};

export default Home;
